import { FormQuestion } from "../type"

export const EN_FORM_QUESTIONS: Record<string, FormQuestion> = {
    favDateActivity: {
        fieldName: "favDateActivity",
        emoji: "🧑‍🤝‍🧑",
        label: `What's your idea of a "perfect" date?`,
        options: [
            { label: "Fine dining, candlelight, looking hot af", value: "fancy_dinner" },
            { label: "Netflix & chill… but actually watching", value: "netflix_chill" },
            { label: "Board games & aggressive rule enforcement", value: "board_game_night" },
            { label: "Running away from our responsibilities", value: "escape" },
        ],
    },
    bathroomEtiquette: {
        fieldName: "bathroomEtiquette",
        emoji: "🚽",
        label: `If you see the toilet paper roll is empty what do you do?`,
        options: [
            { label: "Replace it like a decent human being", value: "replace" },
            { label: "Pretend I didn't see it", value: "ignore" },
            { label: "Take the cardboard roll and make a kazoo", value: "kazoo" },
            { label: "Cry and hope someone else fixes it", value: "cry" },
        ],
    },
    apocalypticSkills: {
        fieldName: "apocalypticSkills",
        emoji: "🧟",
        label: `A zombie apocalypse just started. What's your biggest contribution to survival?`,
        options: [
            { label: "Fighting skills - I am the main character", value: "fighter" },
            { label: "Hiding - I am NOT a main character", value: "hider" },
            { label: "Cooking - We still gotta eat, right?", value: "cook" },
            { label: "Sacrificing myself immediately, no questions", value: "sacrifice" },
        ],
    },
    pizzaTopping: {
        fieldName: "pizzaTopping",
        emoji: "🍕",
        label: `Pineapple on pizza? Choose wisely, this is a deal-breaker.`,
        options: [
            { label: "YES, and I will defend it with my life", value: "yes" },
            { label: "No, and I will judge you forever", value: "no" },
            { label: "I don't care. Just give me food", value: "idc" },
            { label: "Pineapple? I eat pizza with bananas", value: "chaotic" },
        ],
    },
    loveLanguage: {
        fieldName: "loveLanguage",
        emoji: "😘",
        label: `What's your love language? (Aka: How do you demand affection?)`,
        options: [
            { label: "Words of affirmation (Tell me I'm pretty)", value: "words" },
            { label: "Acts of service (Do my laundry, pls)", value: "service" },
            { label: "Gifts (I accept cash, too)", value: "gifts" },
            { label: "Physical touch (Hugs or fights, either works)", value: "touch" },
        ],
    },
    conspiracyBelief: {
        fieldName: "conspiracyBelief",
        emoji: "👽",
        label: `Which conspiracy theory are you most likely to believe?`,
        options: [
            { label: "Birds aren't real. They're government drones.", value: "birds" },
            { label: "The moon landing was staged.", value: "moon" },
            { label: "Bigfoot exists and he owes me money.", value: "bigfoot" },
            { label: "None, I'm normal. (Lies.)", value: "normal" },
        ],
    },
    spicyTolerance: {
        fieldName: "spicyTolerance",
        emoji: "🥵",
        label: `How spicy can you handle your food?`,
        options: [
            { label: "Mild - I cry over black pepper", value: "mild" },
            { label: "Medium - Just a little burn", value: "medium" },
            { label: "Spicy - Pain is temporary, flavor is forever", value: "spicy" },
            { label: "Ghost pepper challenge? Bring it on.", value: "extreme" },
        ],
    },
    pizzaToppingCrime: {
        fieldName: "pizzaToppingCrime",
        emoji: "🍍",
        label: `You just ordered pizza with friends. Someone suggests putting pineapple AND olives on it. What's your move?`,
        options: [
            { label: "Absolutely not. This is an abomination.", value: "no" },
            { label: "I mean, I'll try it, but I won't be happy about it.", value: "reluctant" },
            { label: "Actually, that sounds kinda good?", value: "chaotic_good" },
            { label: "I suggested it. I live for the chaos.", value: "agent_of_chaos" },
        ],
    },
    roadRageResponse: {
        fieldName: "roadRageResponse",
        emoji: "🚗💨",
        label: `You're driving and someone cuts you off. What do you do?`,
        options: [
            { label: "Scream internally but let it go.", value: "internal_screaming" },
            { label: "Aggressively overtake them to establish dominance.", value: "revenge" },
            { label: "Smile and wave like an absolute psycho.", value: "psychological_warfare" },
            { label: "Slowly follow them home just to scare them.", value: "unhinged" },
        ],
    },
    theLastFry: {
        fieldName: "theLastFry",
        emoji: "🍟",
        label: `You're out eating with your partner. There's ONE fry left. What happens next?`,
        options: [
            { label: "I take it. Survival of the fittest.", value: "mine" },
            { label: "I let them have it. Love is sacrifice.", value: "the_giver" },
            { label: "I suggest splitting it like civilized people.", value: "fair" },
            { label: "I eat it in one bite while staring them dead in the eyes.", value: "power_move" },
        ],
    },
    apocalypseSkills: {
        fieldName: "apocalypseSkills",
        emoji: "🧟",
        label: `A zombie apocalypse begins. What's your immediate survival strategy?`,
        options: [
            { label: "Find a weapon. It's me vs. the world now.", value: "fighter" },
            { label: "Find a hiding spot. I am NOT main character material.", value: "hider" },
            { label: "Join the zombies. It's easier that way.", value: "surrender" },
            { label: "Try to negotiate with them. Maybe they just need a friend?", value: "diplomat" },
        ],
    },
    cerealOrMilkFirst: {
        fieldName: "cerealOrMilkFirst",
        emoji: "🥣",
        label: `How do you make cereal?`,
        options: [
            { label: "Cereal first, then milk. Like a normal human.", value: "cereal_first" },
            { label: "Milk first, then cereal. I enjoy watching the world burn.", value: "milk_first" },
            { label: "No milk. Dry cereal straight from the box.", value: "dry" },
            { label: "I don't eat cereal. I just drink coffee and suffer.", value: "coffee_only" },
        ],
    },
    textingStyle: {
        fieldName: "textingStyle",
        emoji: "📱",
        label: `How do you text?`,
        options: [
            { label: "I respond instantly, even at 3 AM.", value: "instant" },
            { label: "I take hours to reply, then say 's'rry just saw this' (I didn't).", value: "delayed" },
            { label: "I send one-word replies and let the conversation die.", value: "short" },
            { label: "I spam memes and voice notes. Good luck keeping up.", value: "chaotic" },
        ],
    },
    dreamPet: {
        fieldName: "dreamPet",
        emoji: "🐍",
        label: `If you could have any pet (no limits), what would it be?`,
        options: [
            { label: "A dog or cat, I have standards.", value: "basic" },
            { label: "A snake, because I like making people uncomfortable.", value: "snake" },
            { label: "A raccoon, for maximum chaos.", value: "raccoon" },
            { label: "A dragon, because I refuse to be realistic.", value: "dragon" },
        ],
    },
    sleepHabits: {
        fieldName: "sleepHabits",
        emoji: "😴",
        label: `What are your sleep habits like?`,
        options: [
            { label: "I sleep 8 hours like a well-adjusted adult.", value: "healthy" },
            { label: "I fall asleep at 3 AM and regret it daily.", value: "nocturnal" },
            { label: "I take random naps at inconvenient times.", value: "napper" },
            { label: "Sleep? Never heard of it.", value: "insomniac" },
        ],
    },
    winningTheLottery: {
        fieldName: "winningTheLottery",
        emoji: "💰",
        label: `You just won the lottery. What's the first thing you do?`,
        options: [
            { label: "Invest it wisely like a responsible adult.", value: "invest" },
            { label: "Disappear forever and start a new life.", value: "vanish" },
            { label: "Buy something stupidly expensive immediately.", value: "impulse_buy" },
            { label: "Tell no one but subtly flex.", value: "flex" },
        ],
    },
    beingGhosted: {
        fieldName: "beingGhosted",
        emoji: "👻",
        label: `You get ghosted by someone you really liked. What's your next move?`,
        options: [
            { label: "Accept it and move on. Their loss.", value: "mature" },
            { label: "Spam them with '?' every hour.", value: "needy" },
            { label: "Block them on everything before they can block me.", value: "block" },
            { label: "Make a dramatic TikTok about my heartbreak.", value: "petty" },
        ],
    },
    howDoYouArgue: {
        fieldName: "howDoYouArgue",
        emoji: "🤬",
        label: `How do you handle arguments?`,
        options: [
            { label: "I cry and hope they feel bad", value: "cry" },
            { label: "I aggressively send passive-aggressive memes", value: "meme_fighter" },
            { label: "I go full lawyer mode with evidence and references", value: "lawyer_mode" },
            { label: "I stare at them until they give up", value: "stare_master" },
        ],
    },
    relationshipFinance: {
        fieldName: "relationshipFinance",
        emoji: "💰",
        label: `Who should pay on the first date?`,
        options: [
            { label: "Whoever asked first, fair is fair", value: "whoever_asks" },
            { label: "Split the bill. We're not in the 1800s", value: "split" },
            { label: "They pay. My presence is the real gift", value: "they_pay" },
            { label: "Fake a bathroom break and disappear", value: "disappear" },
        ],
    },
    yourPetPersonality: {
        fieldName: "yourPetPersonality",
        emoji: "🐾",
        label: `If you were a pet, what would you be?`,
        options: [
            { label: "A dog. Loyal, excitable, easily distracted", value: "dog" },
            { label: "A cat. Independent, judgmental, sleeps too much", value: "cat" },
            { label: "A goldfish. No thoughts, just vibes", value: "goldfish" },
            { label: "A raccoon. Loves trash and bad decisions", value: "raccoon" },
        ],
    },
    onlineShoppingHabits: {
        fieldName: "onlineShoppingHabits",
        emoji: "📦",
        label: `There's a huge sale online. What do you do?`,
        options: [
            { label: "Impulse buy and regret later", value: "impulse_buy" },
            { label: "Put everything in my cart and never check out", value: "cart_hoarder" },
            { label: "Compare prices for 3 hours before deciding", value: "price_comparer" },
            { label: "Ignore it. I am broke", value: "broke" },
        ],
    },
    favoriteChaosFoodCombo: {
        fieldName: "favoriteChaosFoodCombo",
        emoji: "🍽️",
        label: `What's your unhinged food combination?`,
        options: [
            { label: "Fries dipped in ice cream", value: "fries_icecream" },
            { label: "Peanut butter & pickles", value: "pb_pickles" },
            { label: "Cereal with orange juice instead of milk", value: "cereal_orange_juice" },
            { label: "I don't experiment. I fear change", value: "no_experiments" },
        ],
    },
    horrorMovieLogic: {
        fieldName: "horrorMovieLogic",
        emoji: "🎃",
        label: `You're in a horror movie. What's your role?`,
        options: [
            { label: "The one who dies first", value: "dies_first" },
            { label: "The skeptic who refuses to believe anything", value: "skeptic" },
            { label: "The one who makes stupid decisions and survives anyway", value: "lucky_survivor" },
            { label: "The villain. Enough running, I'm the problem now", value: "become_villain" },
        ],
    },
    bathroomDoorStrategy: {
        fieldName: "bathroomDoorStrategy",
        emoji: "🚪",
        label: `You're using a public restroom. There's no lock on the door. What do you do?`,
        options: [
            { label: "Hold it shut with my hand like a gladiator", value: "hold_door" },
            { label: "Make aggressive eye contact with anyone who tries to enter", value: "stare_them_down" },
            { label: "Use one foot to keep it shut while balancing on the toilet", value: "foot_hold" },
            { label: "Accept my fate. If someone walks in, they walk in", value: "accept_fate" },
        ],
    },
    cerealEatingStyle: {
        fieldName: "cerealEatingStyle",
        emoji: "🥣",
        label: `How do you eat your cereal?`,
        options: [
            { label: "Milk first, then cereal like a psycho", value: "milk_first" },
            { label: "Cereal first, the way society intended", value: "cereal_first" },
            { label: "No milk. I eat it dry, like a warrior", value: "dry_cereal" },
            { label: "I drink the milk, then eat the cereal separately", value: "separate" },
        ],
    },
    unexpectedFight: {
        fieldName: "unexpectedFight",
        emoji: "🦵",
        label: `You have to fistfight ONE of the following. Who do you pick?`,
        options: [
            { label: "A kindergartener with unlimited energy", value: "kindergartener" },
            { label: "A goose that has a personal vendetta against you", value: "angry_goose" },
            { label: "A robot programmed to perfectly copy your every move", value: "mirror_robot" },
            { label: "Your own clone, but they have slightly better reflexes", value: "evil_clone" },
        ],
    },
    fakeEmergencyExcuse: {
        fieldName: "fakeEmergencyExcuse",
        emoji: "📞",
        label: `You need to fake an emergency to leave a terrible date. What do you say?`,
        options: [
            { label: `"My pet goldfish is in labor, I have to go!"`, value: "goldfish_labor" },
            { label: `"My grandma just texted me in all caps, this is serious."`, value: "grandma_text" },
            { label: `"My house is on fire. No, you can't come help."`, value: "house_fire" },
            { label: `"I left the oven on, but I live in a hotel, so this is really bad."`, value: "hotel_oven" },
        ],
    },
    zombieApocalypseSkill: {
        fieldName: "zombieApocalypseSkill",
        emoji: "🧟",
        label: `A zombie apocalypse begins. What's your special skill?`,
        options: [
            { label: "I distract zombies by screaming and running in circles", value: "chaos_distraction" },
            { label: "I befriend the zombies. I am their king now.", value: "zombie_king" },
            { label: "I hoard all the snacks and provide zero real help", value: "snack_hoarder" },
            { label: "I die immediately, but dramatically", value: "dramatic_death" },
        ],
    },
    wakingUpWeird: {
        fieldName: "wakingUpWeird",
        emoji: "⏰",
        label: `You wake up and something is... wrong. What is it?`,
        options: [
            { label: "You can only communicate through interpretive dance", value: "dance_only" },
            { label: "Your hands have been replaced with spaghetti", value: "spaghetti_hands" },
            { label: "You now float 2 inches off the ground permanently", value: "hover_mode" },
            { label: "Your internal monologue is now narrated by Morgan Freeman", value: "morgan_freeman_voice" },
        ],
    },
    howYouEatIceCream: {
        fieldName: "howYouEatIceCream",
        emoji: "🍦",
        label: `How do you eat ice cream?`,
        options: [
            { label: "I bite into it like a maniac", value: "ice_cream_biter" },
            { label: "I lick it politely like a normal person", value: "licking_normal" },
            { label: "I let it melt first and drink it", value: "melt_drinker" },
            { label: "I eat the cone first, then regret everything", value: "cone_first" },
        ],
    },
    dramaticBreakupStyle: {
        fieldName: "dramaticBreakupStyle",
        emoji: "💔",
        label: `If you had to break up with someone dramatically, how would you do it?`,
        options: [
            { label: `"It's not you, it's me. Just kidding, it's actually you."`, value: "its_you" },
            { label: `"I'm going on a journey to find myself... and you're not invited."`, value: "find_myself" },
            { label: `"This relationship has been a social experiment. Thank you for your participation."`, value: "social_experiment" },
            { label: `"I'm moving to Antarctica. Alone."`, value: "antarctica" },
        ],
    },
    timeTravelMistake: {
        fieldName: "timeTravelMistake",
        emoji: "⏳",
        label: `You accidentally time travel 200 years into the past. What's the first thing you do?`,
        options: [
            { label: "Invent the 'Rickroll' 200 years early", value: "rickroll_history" },
            { label: "Try to explain WiFi and get burned as a witch", value: "wifi_witch" },
            { label: "Accidentally become royalty because of your weird futuristic slang", value: "accidental_royalty" },
            { label: "Panic, scream, and cry. A lot.", value: "panic_scream" },
        ],
    },
    completelyUselessSuperpower: {
        fieldName: "completelyUselessSuperpower",
        emoji: "🦸‍♂️",
        label: `You get a superpower, but it's completely useless. What is it?`,
        options: [
            { label: "You can teleport… but only 2 inches at a time", value: "tiny_teleport" },
            { label: "You can make any food spicy, but only when nobody wants it spicy", value: "spicy_curse" },
            { label: "You can run really fast… but only backward", value: "fast_backward" },
            { label: "You can perfectly mimic a duck's quack. That's it.", value: "duck_voice" },
        ],
    },
    friendBetrayalScenario: {
        fieldName: "friendBetrayalScenario",
        emoji: "🫱🏽‍🫲🏾",
        label: `Your best friend just betrayed you. What did they do?`,
        options: [
            { label: "They started watching our favorite show without me", value: "netflix_betrayal" },
            { label: "They stole my exact Starbucks order and now I feel robbed", value: "coffee_identity_theft" },
            { label: "They made an inside joke with someone else. How dare they.", value: "inside_joke_traitor" },
            { label: "They stepped on my shoe and didn't say sorry", value: "shoe_disrespect" },
        ],
    },
    wakingUpAsRandomObject: {
        fieldName: "wakingUpAsRandomObject",
        emoji: "🔄",
        label: `You wake up and you are no longer human. What are you?`,
        options: [
            { label: "A Roomba, doomed to clean forever", value: "roomba" },
            { label: "A traffic cone, standing uselessly on the street", value: "traffic_cone" },
            { label: "A lost sock in a washing machine", value: "lost_sock" },
            { label: "A Bluetooth speaker nobody knows how to connect to", value: "bluetooth_speaker" },
        ],
    },
    terribleSuperpower: {
        fieldName: "terribleSuperpower",
        emoji: "🦸",
        label: `You gain a superpower, but it's completely useless. What is it?`,
        options: [
            { label: "You can refill any drink, but only with lukewarm water", value: "lukewarm_water" },
            { label: "You can see 1 second into the future", value: "1_second_future" },
            { label: "You can make any room smell like wet cardboard", value: "wet_cardboard" },
            { label: "You can run at full speed… but only in a perfectly straight line", value: "straight_runner" },
        ],
    },
    worstWayToLoseTrust: {
        fieldName: "worstWayToLoseTrust",
        emoji: "🧐",
        label: `What is the worst way to instantly lose trust in someone?`,
        options: [
            { label: "They say 'trust me' before doing something sketchy", value: "trust_me_liar" },
            { label: "They eat pizza with a fork and knife", value: "fork_and_knife_pizza" },
            { label: "They pronounce GIF as 'jif' with confidence", value: "jif_disaster" },
            { label: "They walk slow in front of you when you're in a hurry", value: "slow_walker" },
        ],
    },
    workplaceLazinessStrategy: {
        fieldName: "workplaceLazinessStrategy",
        emoji: "💼",
        label: `You need to look busy at work but don't want to actually work. What do you do?`,
        options: [
            { label: "Stare at my screen intensely while doing absolutely nothing", value: "screen_stare" },
            { label: "Walk around holding a piece of paper. Nobody questions it.", value: "paper_walk" },
            { label: "Type random things really fast so it looks like I'm coding", value: "fake_typing" },
            { label: "Join a Zoom call and leave my camera off, forever", value: "zoom_ghost" },
        ],
    },
    worstPossibleTattoo: {
        fieldName: "worstPossibleTattoo",
        emoji: "🖋️",
        label: `You have to get a tattoo but it has to be something absolutely terrible. What do you choose?`,
        options: [
            { label: `"Live, Laugh, Laundry" in Comic Sans`, value: "comic_sans_tattoo" },
            { label: `"Insert cool tattoo here" on my forehead`, value: "insert_tattoo" },
            { label: `"WiFi Password: 12345678" on my arm`, value: "wifi_tattoo" },
            { label: `"My Ex's Name in HUGE cursive letters`, value: "ex_name_tattoo" },
        ],
    },
    worstMorningRoutine: {
        fieldName: "worstMorningRoutine",
        emoji: "🌅",
        label: `Which of these is the worst way to start your morning?`,
        options: [
            { label: "Opening your phone and immediately seeing an email from your boss", value: "boss_email" },
            { label: "Realizing you forgot to charge your phone overnight", value: "dead_phone" },
            { label: "Stepping on something wet and you don't know what it is", value: "mystery_wet" },
            { label: "Waking up and immediately stubbing your toe", value: "toe_stub" },
        ],
    },
    chaosSandwich: {
        fieldName: "chaosSandwich",
        emoji: "🥪",
        label: `Which one of these is the worst sandwich ever?`,
        options: [
            { label: "Bread, toothpaste, bread", value: "toothpaste_sandwich" },
            { label: "Bread, ice cubes, bread", value: "ice_cube_sandwich" },
            { label: "Bread, banana, ketchup, bread", value: "banana_ketchup" },
            { label: "Bread, sadness, bread", value: "sadness_sandwich" },
        ],
    },
    accidentalVillainOrigin: {
        fieldName: "accidentalVillainOrigin",
        emoji: "😈",
        label: `If you accidentally became a supervillain, what was your villain origin story?`,
        options: [
            { label: "Someone walked really slow in front of me and I snapped", value: "slow_walker_rage" },
            { label: "My favorite snack got discontinued and I never recovered", value: "snack_discontinued" },
            { label: "A baby gave me a weird look and I took it personally", value: "baby_insult" },
            { label: "I lost an argument in a dream and woke up furious", value: "dream_argument" },
        ],
    },
    emotionalSupportItem: {
        fieldName: "emotionalSupportItem",
        emoji: "🧸",
        label: `You're not yourself without your emotional support item. What is it?`,
        options: [
            { label: "My hoodie. I wear it even when it's 100°F outside", value: "hoodie" },
            { label: "My favorite water bottle. Hydration is my personality", value: "water_bottle" },
            { label: "A snack I carry with me at all times, just in case", value: "emergency_snack" },
            { label: "My headphones. I would rather go deaf than listen to the world", value: "headphones" },
        ],
    },
    weirdestSuperpower: {
        fieldName: "weirdestSuperpower",
        emoji: "🦸‍♂️",
        label: `Which completely useless superpower would you choose?`,
        options: [
            { label: "You can instantly dry wet socks, but only for other people", value: "sock_dryer" },
            { label: "You can make any song play in someone's head, but only at 2 AM", value: "2am_earworm" },
            { label: "You can communicate with houseplants, but they all hate you", value: "plant_whisperer" },
            { label: "You can make any chair slightly uncomfortable, but only when someone else sits on it", value: "chair_curse" },
        ],
    },
    wakingUpAsFood: {
        fieldName: "wakingUpAsFood",
        emoji: "🍕",
        label: `You wake up and realize you've turned into a food item. What are you?`,
        options: [
            { label: "A slightly stale croissant, yet still elegant", value: "stale_croissant" },
            { label: "A single chicken nugget, lost and alone", value: "lonely_nugget" },
            { label: "A bowl of cereal, but someone already poured the milk", value: "soggy_cereal" },
            { label: "A half-eaten slice of pizza, abandoned at a party", value: "forgotten_pizza" },
        ],
    },
    mostAnnoyingVillainPower: {
        fieldName: "mostAnnoyingVillainPower",
        emoji: "😈",
        label: `If you were an annoying supervillain, what would your power be?`,
        options: [
            { label: "I can make someone forget why they walked into a room", value: "forgot_mission" },
            { label: "I can slightly misalign every framed picture in their house", value: "crooked_frames" },
            { label: "I can summon a loud, unskippable ad right before their favorite song", value: "ad_summoner" },
            { label: "I can make their phone buzz, but there's no notification", value: "phantom_vibrate" },
        ],
    },
    cursedCelebrityInteraction: {
        fieldName: "cursedCelebrityInteraction",
        emoji: "🎤",
        label: `You meet your favorite celebrity, but something goes terribly wrong. What happens?`,
        options: [
            { label: "I accidentally call them by the name of their biggest rival", value: "wrong_name" },
            { label: "I trip and fall, taking them down with me", value: "celebrity_tackle" },
            { label: "I say 'I love your work!' but realize I've never seen anything they've done", value: "fake_fan" },
            { label: "I panic and just whisper 'beans' before running away", value: "panic_beans" },
        ],
    },
    reincarnatedAsRandomObject: {
        fieldName: "reincarnatedAsRandomObject",
        emoji: "🔄",
        label: `You get reincarnated, but not as a human. What do you come back as?`,
        options: [
            { label: "A vending machine, forever eating people's money", value: "cursed_vending_machine" },
            { label: "An IKEA chair that nobody can assemble correctly", value: "ikea_chair" },
            { label: "A fridge light that only turns on when the door is closed", value: "fridge_light" },
            { label: "A hotel room TV remote, lost forever", value: "lost_remote" },
        ],
    },
    randomPetPeeve: {
        fieldName: "randomPetPeeve",
        emoji: "😤",
        label: `What's the most irrational thing that instantly annoys you?`,
        options: [
            { label: "When a YouTube ad is longer than the actual video", value: "long_ad" },
            { label: "When someone replies 'K' to a long message", value: "k_response" },
            { label: "When people don't speed up at the end of an escalator", value: "escalator_slowpoke" },
            { label: "When someone breathes way too loud for no reason", value: "loud_breathing" },
        ],
    },
    worstPossibleNickname: {
        fieldName: "worstPossibleNickname",
        emoji: "📛",
        label: `Your friends have decided to give you a nickname, but it's terrible. What is it?`,
        options: [
            { label: "Moist", value: "moist" },
            { label: "Crusty", value: "crusty" },
            { label: "Grandpa Energy", value: "grandpa_energy" },
            { label: "Biscuit Boy/Girl", value: "biscuit_person" },
        ],
    },
    workplaceSuperpower: {
        fieldName: "workplaceSuperpower",
        emoji: "💼",
        label: `You gain a superpower, but it's only useful at work. What is it?`,
        options: [
            { label: "I can perfectly time bathroom breaks to avoid doing actual work", value: "bathroom_timing" },
            { label: "I can make my keyboard sound 10x louder so people think I'm working hard", value: "loud_typing" },
            { label: "I can make my boss walk away the second they try to assign me a task", value: "boss_repellent" },
            { label: "I can instantly mute the most annoying coworker", value: "coworker_mute" },
        ],
    },
    weirdestTimeTravelMission: {
        fieldName: "weirdestTimeTravelMission",
        emoji: "⏳",
        label: `You've been sent back in time for one very specific reason. What is it?`,
        options: [
            { label: "To stop the first person from ever clapping on a plane", value: "clap_stopper" },
            { label: "To make sure flip phones never go out of style", value: "flip_phone_savior" },
            { label: "To plant an ancient meme so historians are confused", value: "historical_meme" },
            { label: "To make sure 'Shrek 2' still gets made", value: "shrek_2_protector" },
        ],
    },
} as const
