import { FormQuestion } from "../type"

export const ID_FORM_QUESTIONS: Record<string, FormQuestion> = {
    favDateActivity: {
        fieldName: "favDateActivity",
        emoji: "💑",
        label: `Kalau nge-date, paling seru ngapain?`,
        options: [
            { label: "Makan di restoran mahal biar estetik 🤩", value: "fancy_dinner" },
            { label: "Netflix & chill… sambil makan Indomie", value: "netflix_indomie" },
            { label: "Main board game sampe ada yang ngambek 😡", value: "board_game" },
            { label: "Jalan-jalan ke mall sampe kaki pegel 🏃‍♂️", value: "mall" },
        ],
    },
    bathroomEtiquette: {
        fieldName: "bathroomEtiquette",
        emoji: "🚿",
        label: `Di toilet umum, kamu tipe yang...?`,
        options: [
            { label: "Guyur dulu sebelum duduk (biar steril) 🚰", value: "guyur_dulu" },
            { label: "Langsung duduk, biarin aja", value: "langsung" },
            { label: "Manggil emak buat ambilin air", value: "manggil_emak" },
            { label: "Mikirin eksistensi hidup sebelum cebok 🤔", value: "mikir_dulu" },
        ],
    },
    apocalypticSkills: {
        fieldName: "apocalypticSkills",
        emoji: "🧟",
        label: `Tiba-tiba ada serangan zombie, apa yang bakal kamu lakukan?`,
        options: [
            { label: "Lawan pake golok! Aku bukan orang biasa! ⚔️", value: "fighter" },
            { label: "Ngumpet di Indomaret, biar ada stok mie instan", value: "hider" },
            { label: "Masak Indomie buat zombie, biar kita damai 🍜", value: "cook" },
            { label: "Langsung nyerah aja, hidup udah capek", value: "sacrifice" },
        ],
    },
    indomiePreference: {
        fieldName: "indomiePreference",
        emoji: "🍜",
        label: `Makan Indomie paling enak gimana?`,
        options: [
            { label: "Kuah panas, pake telur biar nikmat", value: "kuah" },
            { label: "Goreng, terus ditambah nasi! 🍚", value: "goreng" },
            { label: "Dimakan mentah langsung kaya ciki", value: "mentah" },
            { label: "Dijadiin Indomie burger, coba-coba aja", value: "burger" },
        ],
    },
    ayamGeprekLevel: {
        fieldName: "ayamGeprekLevel",
        emoji: "🌶️",
        label: `Kalau makan ayam geprek, level pedasnya...?`,
        options: [
            { label: "Level 1 aja, takut diare 🥲", value: "level1" },
            { label: "Level 5, masih aman sih", value: "level5" },
            { label: "Level 10! Keringetan itu nikmat", value: "level10" },
            { label: "Level 20++, biar hidup ada tantangan 🔥", value: "level20" },
        ],
    },
    kerokanOrNot: {
        fieldName: "kerokanOrNot",
        emoji: "🪃",
        label: `Kalau masuk angin, apa yang kamu lakukan?`,
        options: [
            { label: "Langsung kerokan, wajib! 🟥🟧", value: "kerokan" },
            { label: "Minum tolak angin dulu", value: "tolak_angin" },
            { label: "Tidur aja, biar sembuh sendiri", value: "tidur" },
            { label: "Masuk angin tuh mitos...", value: "mitos" },
        ],
    },
    idealVacation: {
        fieldName: "idealVacation",
        emoji: "🏝️",
        label: `Kalau liburan bareng pasangan, paling enak ke mana?`,
        options: [
            { label: "Bali! Sunset, pantai, chill...", value: "bali" },
            { label: "Bandung, dingin-dingin romantis", value: "bandung" },
            { label: "Jogja, vibesnya beda", value: "jogja" },
            { label: "Staycation aja di kosan", value: "staycation" },
        ],
    },
    relationshipFights: {
        fieldName: "relationshipFights",
        emoji: "🤬",
        label: `Kalau lagi berantem, kamu biasanya...?`,
        options: [
            { label: "Langsung ngobrol biar cepet baikan", value: "ngobrol" },
            { label: "Diem-dieman dulu, biar ada vibe sinetron", value: "dieman" },
            { label: "Spam meme sampe doi ngakak 😂", value: "meme" },
            { label: "Ngilang, biar doi sadar kalo aku berharga", value: "ngilang" },
        ],
    },
    petChoice: {
        fieldName: "petChoice",
        emoji: "🐾",
        label: `Kalau bisa punya peliharaan, pilih apa?`,
        options: [
            { label: "Kucing, lucu tapi kadang jahat 🐱", value: "cat" },
            { label: "Anjing, setia dan manja 🐶", value: "dog" },
            { label: "Ayam, biar tiap pagi ada alarm alami 🐔", value: "chicken" },
            { label: "Punya pocong peliharaan biar hemat listrik 👻", value: "pocong" },
        ],
    },
    howToEatRice: {
        fieldName: "howToEatRice",
        emoji: "🍚",
        label: `Nasi tuh paling enak dimakan pake apa?`,
        options: [
            { label: "Ayam geprek, combo mantap!", value: "geprek" },
            { label: "Telur dadar, yang penting ada lauk", value: "telur" },
            { label: "Kecap + garam (sad meal)", value: "kecap" },
            { label: "Nasi anget doang (minimalis)", value: "polos" },
        ],
    },
    baksoOrMieAyam: {
        fieldName: "baksoOrMieAyam",
        emoji: "🍜",
        label: `Lagi laper banget. Pilih yang mana?`,
        options: [
            { label: "Bakso, kuahnya seger 🍡", value: "bakso" },
            { label: "Mie ayam, toppingnya banyak! 🥢", value: "mie_ayam" },
            { label: "Dua-duanya, aku anak sultan", value: "dua" },
            { label: "Gua makan nasi pake kecap aja 🥲", value: "irit" },
        ],
    },
    ghostEncounter: {
        fieldName: "ghostEncounter",
        emoji: "👻",
        label: `Tiba-tiba ketemu kuntilanak di jalan. Apa reaksi lo?`,
        options: [
            { label: "Lari sekenceng-kencengnya 🏃‍♂️", value: "lari" },
            { label: "Teriak 'permisi ya kak!' 😬", value: "permisi" },
            { label: "Nawarin rokok biar dia chill 🚬", value: "rokok" },
            { label: "Gue cuekin, biar dia insecure", value: "cuek" },
        ],
    },
    losingSignal: {
        fieldName: "losingSignal",
        emoji: "📶",
        label: `Lagi chatting penting banget, terus sinyal ilang. Apa yang lo lakuin?`,
        options: [
            { label: "Restart HP, pasti berhasil 🔄", value: "restart" },
            { label: "Pindah ke tempat lebih tinggi, kaya Naruto 🌄", value: "pindah" },
            { label: "Chat ulang dari awal, males nunggu", value: "ulang" },
            { label: "Pasrah, mungkin ini pertanda dari semesta", value: "pasrah" },
        ],
    },
    relationshipFinance: {
        fieldName: "relationshipFinance",
        emoji: "💸",
        label: `Siapa yang harus bayar pas kencan pertama?`,
        options: [
            { label: "Cowok dong, gentlemen vibes", value: "cowok" },
            { label: "Cewek, biar beda aja 😎", value: "cewek" },
            { label: "Patungan, kita kan tim", value: "split" },
            { label: "Gua ngilang sebelum bayar 🚶‍♂️", value: "ngilang" },
        ],
    },
    karaokeStyle: {
        fieldName: "karaokeStyle",
        emoji: "🎤",
        label: `Kalo karaokean, lo tipe yang...?`,
        options: [
            { label: "Nyanyi all out, suara pas-pasan bodo amat!", value: "all_out" },
            { label: "Cuma milih lagu tapi nggak nyanyi", value: "pilih_lagu" },
            { label: "Nunggu lagu mellow biar bisa curhat 🥀", value: "mellow" },
            { label: "Nari doang, nggak ikutan nyanyi", value: "nari" },
        ],
    },
    trafficJamReaction: {
        fieldName: "trafficJamReaction",
        emoji: "🚗",
        label: `Lagi macet total, terus lo...?`,
        options: [
            { label: "Diem aja, pasrah", value: "pasrah" },
            { label: "Nyetel lagu keras-keras biar happy 🎶", value: "musik" },
            { label: "Ngomel-ngomel ke supir (walaupun naik Gojek)", value: "ngomel" },
            { label: "Nyoba tidur tapi gagal", value: "tidur" },
        ],
    },
    horrorMovieStyle: {
        fieldName: "horrorMovieStyle",
        emoji: "🎥",
        label: `Kalo nonton film horror, lo tipe yang...?`,
        options: [
            { label: "Tutup mata, tapi intip dikit", value: "intip" },
            { label: "Teriak duluan sebelum hantunya muncul", value: "teriak" },
            { label: "Santai, malah ngakak", value: "ngakak" },
            { label: "Tidur, film horror nggak efek ke gue", value: "tidur" },
        ],
    },
    nasiGorengStyle: {
        fieldName: "nasiGorengStyle",
        emoji: "🍳",
        label: `Nasi goreng enaknya pake apa?`,
        options: [
            { label: "Telur ceplok, wajib!", value: "telur" },
            { label: "Makan polosan aja, minimalis", value: "polos" },
            { label: "Dibanjur kecap biar manis", value: "kecap" },
            { label: "Tambah cabe biar berkeringat! 🌶️", value: "pedas" },
        ],
    },
    yourSleepHabits: {
        fieldName: "yourSleepHabits",
        emoji: "😴",
        label: `Gimana kebiasaan tidur lo?`,
        options: [
            { label: "Tidur teratur, jam 10 udah bobok", value: "teratur" },
            { label: "Tidur jam 3 pagi, bangun siang", value: "begadang" },
            { label: "Tidur cuma buat ngisi waktu kosong", value: "random" },
            { label: "Gak tidur, gue vampir", value: "insomnia" },
        ],
    },
    onlineShopping: {
        fieldName: "onlineShopping",
        emoji: "📦",
        label: `Liat diskon gede di e-commerce, lo...?`,
        options: [
            { label: "Langsung checkout, rezeki nggak boleh ditolak!", value: "checkout" },
            { label: "Masukin keranjang, tapi nggak beli", value: "keranjang" },
            { label: "Bandingin harga di 5 toko dulu 🧐", value: "bandingin" },
            { label: "Nunggu gajian baru beli 🥲", value: "nunggu_gajian" },
        ],
    },
    sambalToleransi: {
        fieldName: "sambalToleransi",
        emoji: "🌶️",
        label: `Seberapa pedas sambal yang lo sanggup makan?`,
        options: [
            { label: "Cuma sambal bawang, lebih dari itu kapok", value: "bawang" },
            { label: "Sambal terasi, masih aman dikit", value: "terasi" },
            { label: "Sambal setan! Airmata & keringat bersatu!", value: "setan" },
            { label: "Sambal? Gue minum BonCabe langsung", value: "boncabe" },
        ],
    },
    extremeBoardGame: {
        fieldName: "extremeBoardGame",
        emoji: "🎲",
        label: `Kalau main board game sama pasangan, lo tipe yang...?`,
        options: [
            { label: "Santai, yang penting have fun", value: "santai" },
            { label: "Gue main serius, gak ada ampun", value: "serius" },
            { label: "Curang dikit boleh dong 😉", value: "curang" },
            { label: "Ngambek kalo kalah, harus menang!", value: "ngambek" },
        ],
    },
    annoyingHabits: {
        fieldName: "annoyingHabits",
        emoji: "🤨",
        label: `Kebiasaan paling ngeselin yang lo punya?`,
        options: [
            { label: "Nggak bales chat, tapi aktif di sosmed", value: "no_reply" },
            { label: "Ngambil makanan orang tanpa izin", value: "food_stealer" },
            { label: "Ngupil terus lupa cuci tangan", value: "ngupil" },
            { label: "Ngorok keras sampe bikin gempa", value: "ngorok" },
        ],
    },
    durianOpinion: {
        fieldName: "durianOpinion",
        emoji: "🍈",
        label: `Durian itu...?`,
        options: [
            { label: "Surga dunia! Bau harum banget", value: "suka" },
            { label: "Bau kamar mandi umum, nggak suka", value: "benci" },
            { label: "Makan kalau gratis aja", value: "gratis" },
            { label: "Durian es krim oke, yang asli NOPE", value: "eskrim" },
        ],
    },
    phoneBattery: {
        fieldName: "phoneBattery",
        emoji: "🔋",
        label: `Baterai HP tinggal 2%. Apa yang lo lakuin?`,
        options: [
            { label: "Panikan! Langsung cari colokan", value: "panik" },
            { label: "Mode hemat daya, jaga-jaga", value: "hemat" },
            { label: "Santai, mati ya mati", value: "mati_aja" },
            { label: "Malah nonton TikTok sampe beneran mati", value: "tiktok" },
        ],
    },
    warungIndomieStyle: {
        fieldName: "warungIndomieStyle",
        emoji: "🍜",
        label: `Makan Indomie di warung tuh wajib pake...?`,
        options: [
            { label: "Telur ceplok, biar mantep!", value: "telur" },
            { label: "Kornet, favorit sejuta umat", value: "kornet" },
            { label: "Keju! Biar fancy dikit 🧀", value: "keju" },
            { label: "Cuma kuah doang, anak kos mode", value: "polos" },
        ],
    },
    sleepPosition: {
        fieldName: "sleepPosition",
        emoji: "🛏️",
        label: `Posisi tidur favorit lo?`,
        options: [
            { label: "Telentang, ala mayat 🛌", value: "telentang" },
            { label: "Meringkuk kaya udang 🦐", value: "udang" },
            { label: "Perut ke bawah, napas dikit-dikit", value: "perut" },
            { label: "Gak punya posisi tetap, kayak ninja", value: "random" },
        ],
    },
    waitingForFood: {
        fieldName: "waitingForFood",
        emoji: "⌛",
        label: `Lagi laper berat, terus makanan lo lama banget dateng. Apa yang lo lakuin?`,
        options: [
            { label: "Diem aja, sabar menunggu", value: "sabar" },
            { label: "Curi makanan temen duluan", value: "curi" },
            { label: "Main HP biar gak kepikiran", value: "main_hp" },
            { label: "Komplen ke abang warung biar buru-buru", value: "komplen" },
        ],
    },
    horrorSuperpower: {
        fieldName: "horrorSuperpower",
        emoji: "🦸‍♂️",
        label: `Kalau punya kekuatan di film horror, lo lebih suka yang mana?`,
        options: [
            { label: "Bisa ngilang biar gak dikejar hantu", value: "ngilang" },
            { label: "Bisa ngobrol sama hantu, jadi bestie 👻", value: "bestie_hantu" },
            { label: "Kekuatan tinju biar hantunya babak belur", value: "tinju" },
            { label: "Slow motion kaya di iklan sabun", value: "slow_mo" },
        ],
    },
    karaokeSongChoice: {
        fieldName: "karaokeSongChoice",
        emoji: "🎤",
        label: `Kalau disuruh nyanyi di karaoke, lagu wajib lo apa?`,
        options: [
            { label: "Dewa 19 - Kangen 🎸", value: "dewa" },
            { label: "Tulus - Hati-hati di Jalan 😭", value: "tulus" },
            { label: "Ayamku - Denny Caknan 🐔", value: "ayamku" },
            { label: "Lagu JKT48 biar semangat!", value: "jkt48" },
        ],
    },
    martabakTopping: {
        fieldName: "martabakTopping",
        emoji: "🥞",
        label: `Martabak manis paling enak pake topping apa?`,
        options: [
            { label: "Coklat kacang, klasik terbaik", value: "coklat_kacang" },
            { label: "Keju doang, elegan", value: "keju" },
            { label: "Campur SEMUANYA sampe berat banget", value: "campur" },
            { label: "Gak suka martabak, aku agen asing", value: "anti_martabak" },
        ],
    },
    streetFoodHygiene: {
        fieldName: "streetFoodHygiene",
        emoji: "🍢",
        label: `Liat abang jualan gorengan tangannya abis megang duit, reaksi lo?`,
        options: [
            { label: "Gas aja, virus bisa kalah sama minyak goreng", value: "gas" },
            { label: "Minta dia cuci tangan dulu", value: "cuci" },
            { label: "Diem tapi dalem hati nangis", value: "nangis" },
            { label: "Langsung pergi, perut gua berharga", value: "pergi" },
        ],
    },
    cheatingOnExam: {
        fieldName: "cheatingOnExam",
        emoji: "📝",
        label: `Ujian, lo tipe yang...?`,
        options: [
            { label: "Belajar mati-matian kayak anak sholeh", value: "belajar" },
            { label: "Contek dikit gapapa kan ya?", value: "contek" },
            { label: "Bikin catatan kecil di botol minum", value: "botol" },
            { label: "Minta jawaban terang-terangan", value: "minta" },
        ],
    },
    indomieCursed: {
        fieldName: "indomieCursed",
        emoji: "🍜",
        label: `Cara makan Indomie paling GAK MASUK AKAL tapi lo tetep lakuin?`,
        options: [
            { label: "Dijadiin sandwich pake roti", value: "sandwich" },
            { label: "Dibuat jadi pancake", value: "pancake" },
            { label: "Dimasukin ES BATU biar dingin", value: "es_batu" },
            { label: "Makan Indomie pake nasi (anak Indonesia sejati)", value: "nasi" },
        ],
    },
    ghostDare: {
        fieldName: "ghostDare",
        emoji: "👻",
        label: `Disuruh uji nyali di kuburan, lo bakal...?`,
        options: [
            { label: "Gas! Gak takut!", value: "gas" },
            { label: "Bilang 'Sorry ya bang, numpang lewat'", value: "permisi" },
            { label: "Langsung kabur sebelum mulai", value: "kabur" },
            { label: "Pura-pura kesurupan biar dipulangin", value: "kesurupan" },
        ],
    },
    foodStealing: {
        fieldName: "foodStealing",
        emoji: "🍕",
        label: `Lo sering ngambil makanan orang lain tanpa izin?`,
        options: [
            { label: "Sering, kalo gak ketahuan artinya halal", value: "sering" },
            { label: "Kadang, tapi cuma ke temen deket", value: "kadang" },
            { label: "Gue cuma minta, gak nyolong!", value: "minta" },
            { label: "Gue lebih sering jadi korban", value: "korban" },
        ],
    },
    breakUpMethod: {
        fieldName: "breakUpMethod",
        emoji: "💔",
        label: `Kalo putus, cara terbaik menurut lo...?`,
        options: [
            { label: "Ngomong langsung, kayak orang dewasa", value: "dewasa" },
            { label: "Ngilang aja sampe doi ngerti sendiri", value: "ghosting" },
            { label: "Putus lewat chat biar nggak awkward", value: "chat" },
            { label: "Bikin doi kesel dulu biar dia yang mutusin", value: "manipulasi" },
        ],
    },
    washingDishes: {
        fieldName: "washingDishes",
        emoji: "🍽️",
        label: `Lagi numpang makan di rumah temen, lo bakal...?`,
        options: [
            { label: "Cuci piring sendiri, biar sopan", value: "cuci" },
            { label: "Tinggalin aja, biar tuan rumah yang cuci", value: "tinggalin" },
            { label: "Gue bantu nyusun piring, minimal effort", value: "minimal" },
            { label: "Pura-pura sibuk biar gak disuruh cuci", value: "pura_pura" },
        ],
    },
    horrorMovieSurvival: {
        fieldName: "horrorMovieSurvival",
        emoji: "🎬",
        label: `Lo kalo jadi karakter di film horror, bakal...?`,
        options: [
            { label: "Jadi yang mati pertama", value: "mati_duluan" },
            { label: "Survive sampe akhir, tapi trauma", value: "selamat" },
            { label: "Jadi yang sok berani tapi kena karma", value: "karma" },
            { label: "Join sama hantunya, males kabur", value: "gabung" },
        ],
    },
    spicyRelationship: {
        fieldName: "spicyRelationship",
        emoji: "🔥",
        label: `Kalo pacaran, lo tipe...?`,
        options: [
            { label: "Bucin akut, 24/7 chat", value: "bucin" },
            { label: "Santai aja, gak perlu tiap hari kontak", value: "santai" },
            { label: "Doyan ngegas kalo telat bales", value: "ngegas" },
            { label: "Gue sering lupa balas chat 😅", value: "lupa" },
        ],
    },
    sideOfBed: {
        fieldName: "sideOfBed",
        emoji: "🛏️",
        label: `Kalo tidur bareng, lo harus di sisi mana?`,
        options: [
            { label: "Kiri, pokoknya harus kiri!", value: "kiri" },
            { label: "Kanan, gak bisa tidur kalo di kiri", value: "kanan" },
            { label: "Gak peduli, yang penting empuk", value: "bebas" },
            { label: "Gak peduli, karena gue nguasain seluruh kasur", value: "diktator" },
        ],
    },
    reactionToBeingIgnored: {
        fieldName: "reactionToBeingIgnored",
        emoji: "😠",
        label: `Kalo lagi chat terus doi lama balesnya, lo bakal...?`,
        options: [
            { label: "Santai aja, mungkin dia sibuk", value: "santai" },
            { label: "Nungguin sambil stalking story", value: "stalking" },
            { label: "Chat '??' biar dia tau gue nunggu", value: "question_marks" },
            { label: "Bales lebih lama biar impas", value: "balas_dendam" },
        ],
    },
    whoEatsTheLastBite: {
        fieldName: "whoEatsTheLastBite",
        emoji: "🍕",
        label: `Lagi makan berdua, tinggal satu suapan terakhir. Siapa yang harus makan?`,
        options: [
            { label: "Gue, karena gue yang paling butuh", value: "gue" },
            { label: "Doi, biar keliatan sweet", value: "doi" },
            { label: "Dipisah biar adil", value: "dipisah" },
            { label: "Gak ada yang makan sampe basi", value: "gak_ada" },
        ],
    },
    reactionToEmbarrassment: {
        fieldName: "reactionToEmbarrassment",
        emoji: "😳",
        label: `Lagi jalan di mall, tiba-tiba lo kepleset di depan banyak orang. Lo bakal...?`,
        options: [
            { label: "Cepet-cepet bangun pura-pura gak terjadi apa-apa", value: "pura_pura" },
            { label: "Ketawa sendiri biar gak malu", value: "ketawa" },
            { label: "Ngeliatin lantai dengan penuh kebencian", value: "lantai" },
            { label: "Langsung kabur ke toilet terdekat", value: "kabur" },
        ],
    },
    spicyFoodCompetition: {
        fieldName: "spicyFoodCompetition",
        emoji: "🌶️",
        label: `Ada tantangan makan mie pedes level 100, lo...?`,
        options: [
            { label: "Gas! Pantang mundur", value: "gas" },
            { label: "Coba dikit, terus nyesel", value: "nyesel" },
            { label: "Nonton temen menderita sambil ketawa", value: "nonton" },
            { label: "Gak mau, perut gua bukan besi", value: "menolak" },
        ],
    },
    childhoodCartoon: {
        fieldName: "childhoodCartoon",
        emoji: "📺",
        label: `Kartun masa kecil yang paling lo inget?`,
        options: [
            { label: "Spongebob, golden era TV", value: "spongebob" },
            { label: "Doraemon, setiap minggu wajib nonton", value: "doraemon" },
            { label: "Upin Ipin, bestie masa kecil", value: "upin_ipin" },
            { label: "Tom & Jerry, isinya cuma kejar-kejaran", value: "tom_jerry" },
        ],
    },
    reactionToSeeingCelebrity: {
        fieldName: "reactionToSeeingCelebrity",
        emoji: "🤩",
        label: `Ketemu artis terkenal di tempat umum, lo bakal...?`,
        options: [
            { label: "Minta foto dong!", value: "foto" },
            { label: "Liatin aja dari jauh, biar gak ganggu", value: "liatin" },
            { label: "Pura-pura gak peduli, padahal excited", value: "sok_cuek" },
            { label: "Gak kenal, cuek aja", value: "gak_kenal" },
        ],
    },
    findingMoneyOnTheGround: {
        fieldName: "findingMoneyOnTheGround",
        emoji: "💰",
        label: `Lagi jalan, nemu duit 100 ribu di jalan. Lo bakal...?`,
        options: [
            { label: "Ambil dong! Rezeki jangan ditolak", value: "ambil" },
            { label: "Liat sekitar dulu, takut ada yang liat", value: "hati_hati" },
            { label: "Cari pemiliknya, takut karma", value: "jujur" },
            { label: "Diamkan, takut itu jebakan polisi", value: "jebakan" },
        ],
    },
    ketchupOrChiliSauce: {
        fieldName: "ketchupOrChiliSauce",
        emoji: "🍅",
        label: `Lo tim kecap atau tim saus sambal?`,
        options: [
            { label: "Tim kecap, yang penting manis", value: "kecap" },
            { label: "Tim saus sambal, makin pedes makin enak", value: "sambal" },
            { label: "Campur dua-duanya biar maksimal", value: "campur" },
            { label: "Gak suka dua-duanya, anak alien", value: "gak_suka" },
        ],
    },
    gettingCaughtSleepingInClass: {
        fieldName: "gettingCaughtSleepingInClass",
        emoji: "😴",
        label: `Ketiduran di kelas, terus ketauan guru. Lo bakal...?`,
        options: [
            { label: "Ngaku aja, 'Maaf Pak/Bu, ngantuk banget'", value: "ngaku" },
            { label: "Pura-pura melek tapi mata masih setengah ketutup", value: "melek_pura" },
            { label: "Langsung jawab 'Saya denger kok Bu/Pak!'", value: "jawab_dulu" },
            { label: "Nuduh temen sebelah yang sebenernya gak salah", value: "nuduh" },
        ],
    },
    teoriKonspirasiNasiPadang: {
        fieldName: "teoriKonspirasiNasiPadang",
        emoji: "🍛",
        label: `Kenapa nasi Padang kalau dibungkus porsinya lebih banyak?`,
        options: [
            { label: "Efek ilusi optik dari kertas minyak", value: "ilusi_optik" },
            { label: "Penjualnya punya kalkulasi rahasia", value: "kalkulasi_rahasia" },
            { label: "Orang yang makan di tempat kena pajak ‘jatah makan di sana’", value: "pajak_makan" },
            { label: "Ini bukan pertanyaan, ini keajaiban dunia", value: "keajaiban_dunia" },
        ],
    },
    gayaTidurAneh: {
        fieldName: "gayaTidurAneh",
        emoji: "🛏️",
        label: `Gaya tidurmu yang paling aneh adalah...?`,
        options: [
            { label: "Terlentang kayak mayat di rumah sakit", value: "mayat" },
            { label: "Meringkuk seperti bayi kedinginan", value: "bayi" },
            { label: "Gulingan muter-muter kayak gaspol di kasur", value: "gulingan" },
            { label: "Posisi ketindihan setan, tapi gak ada yang nindihin", value: "ketindihan_halu" },
        ],
    },
    pilihanKerjaanAneh: {
        fieldName: "pilihanKerjaanAneh",
        emoji: "👷",
        label: `Kalau tiba-tiba disuruh kerja di bidang yang aneh, mana yang paling mungkin kamu ambil?`,
        options: [
            { label: "Joki ngerjain tugas anak sekolah", value: "joki_tugas" },
            { label: "Pengawas antrian Indomaret jam promo", value: "pengawas_indomaret" },
            { label: "Tukang kasih tau ‘wifi-nya nyala nggak?’ di kosan", value: "cek_wifi" },
            { label: "Kasir tapi tiap pembeli datang aku nyanyi kayak di musical", value: "kasir_musical" },
        ],
    },
    reaksiLiatCicakJatuh: {
        fieldName: "reaksiLiatCicakJatuh",
        emoji: "🦎",
        label: `Kamu lagi makan, tiba-tiba cicak jatuh dari langit-langit. Apa yang kamu lakukan?`,
        options: [
            { label: "Langsung lompat panik, teriak-teriak", value: "lompat_panik" },
            { label: "Tenang, tapi di dalam hati udah chaos", value: "panik_dalam_hati" },
            { label: "Cuek, cicaknya juga lagi struggling hidup", value: "cuek" },
            { label: "Mikirin karma apa yang bikin cicak ini jatuh pas aku makan", value: "karma_cicak" },
        ],
    },
    kendaraanPalingNyeleneh: {
        fieldName: "kendaraanPalingNyeleneh",
        emoji: "🚲",
        label: `Kalau kendaraan biasa sudah membosankan, apa alat transportasi terbaik buatmu?`,
        options: [
            { label: "Odong-odong biar tiap perjalanan ada backsound", value: "odong_odong" },
            { label: "Naik becak tapi drivernya robot AI", value: "becak_ai" },
            { label: "Naik bajaj, karena sensasi jogetnya beda", value: "bajaj" },
            { label: "Nge-skateboard sambil pegang tali ditarik motor", value: "skateboard_tarik" },
        ],
    },
    alasanPutusPalingReceh: {
        fieldName: "alasanPutusPalingReceh",
        emoji: "💔",
        label: `Mana alasan putus yang paling receh tapi masuk akal?`,
        options: [
            { label: `"Dia makan nasi pake sendok aja, nggak pake garpu juga. Aneh."`, value: "sendok_doang" },
            { label: `"Dia nggak pernah nanya ‘Udah makan belum?’ Aku butuh kepedulian itu."`, value: "gak_nanya_makan" },
            { label: `"Dia bilang martabak manis lebih enak dari martabak telur. Aku nggak bisa terima."`, value: "martabak_debat" },
            { label: `"Dia ketawa kayak suara knalpot racing. Bikin sakit kepala."`, value: "ketawa_knalpot" },
        ],
    },
    superpowerGakBerguna: {
        fieldName: "superpowerGakBerguna",
        emoji: "🦸",
        label: `Kalau bisa punya superpower yang nggak berguna sama sekali, kamu pilih yang mana?`,
        options: [
            { label: "Bisa mengingat semua harga Indomie di setiap warung", value: "harga_indomie" },
            { label: "Bisa tahu siapa yang nyalain motor pas Subuh", value: "motor_subuh" },
            { label: "Bisa bikin charger HP nempel terus di dinding tanpa jatuh", value: "charger_nempel" },
            { label: "Bisa ngedipin dua mata sekaligus kayak lampu hazard", value: "lampu_hazard" },
        ],
    },
    kebiasaanOrangIndoPalingNyebelin: {
        fieldName: "kebiasaanOrangIndoPalingNyebelin",
        emoji: "🇮🇩",
        label: `Kebiasaan khas orang Indo yang paling nyebelin menurutmu?`,
        options: [
            { label: "Nanya ‘udah makan belum?’ padahal nggak mau ngajak makan", value: "udah_makan_belum" },
            { label: "Ngaret 2 jam tapi masih santai", value: "ngaret" },
            { label: "Nanya ‘Kapan nikah?’ ke orang yang baru putus", value: "kapan_nikah" },
            { label: "Bilang ‘5 menit lagi nyampe’ padahal baru mandi", value: "bohong_5_menit" },
        ],
    },
    reaksiLiatBayanganSerem: {
        fieldName: "reaksiLiatBayanganSerem",
        emoji: "👻",
        label: `Kamu sendirian, terus ngeliat bayangan aneh di tembok. Apa yang kamu lakukan?`,
        options: [
            { label: "Langsung tutup mata, kalau nggak liat berarti nggak ada", value: "tutup_mata" },
            { label: "Baca doa, tapi sambil lari ke kamar", value: "baca_doa_lari" },
            { label: "Nanya, ‘Siapa tuh?’ padahal nggak mau tau jawabannya", value: "nanya_tapi_takut" },
            { label: "Nge-record buat konten biar viral", value: "record_konten" },
        ],
    },
    kebiasaanMandiAneh: {
        fieldName: "kebiasaanMandiAneh",
        emoji: "🚿",
        label: `Kebiasaan mandi mana yang paling aneh tapi entah kenapa lu lakuin?`,
        options: [
            { label: "Gosok gigi dulu sebelum mandi biar fresh", value: "gosok_gigi_dulu" },
            { label: "Diem bengong dulu di kamar mandi 10 menit sebelum mulai", value: "bengong_10_menit" },
            { label: "Nyanyi konser full album sambil shower", value: "konser_mandi" },
            { label: "Ngatur suhu air sampe sempurna, baru bisa mulai", value: "ngatur_suhu" },
        ],
    },
    reaksiKetemuTemenDuluan: {
        fieldName: "reaksiKetemuTemenDuluan",
        emoji: "👀",
        label: `Lagi jalan di mall, liat temen duluan. Apa yang lu lakuin?`,
        options: [
            { label: "Langsung nyamperin & teriak ‘WOOY!’", value: "teriak_woy" },
            { label: "Pura-pura nggak liat, tunggu mereka sadar duluan", value: "pura_pura_gak_liat" },
            { label: "Beralih jalur biar nggak usah nyapa", value: "menghindar" },
            { label: "Chat dia ‘Woy, gua liat lu nih’ biar aman", value: "chat_woy" },
        ],
    },
    caraMarahinOrang: {
        fieldName: "caraMarahinOrang",
        emoji: "😤",
        label: `Kalau lu marah sama seseorang, lu bakal...?`,
        options: [
            { label: "Diamin sampe mereka sadar sendiri", value: "silent_treatment" },
            { label: "Kirim meme pasif-agresif di grup", value: "meme_pasif_agresif" },
            { label: "Bikin instastory quote galau biar kena sindir", value: "sindir_instastory" },
            { label: "Langsung konfrontasi dengan PowerPoint berisi bukti", value: "powerpoint_drama" },
        ],
    },
    tipeBangunTidur: {
        fieldName: "tipeBangunTidur",
        emoji: "⏰",
        label: `Lu tipe yang bangun tidur langsung...?`,
        options: [
            { label: "Cek HP dulu walaupun nggak ada notifikasi", value: "cek_hp_dulu" },
            { label: "Tiduran lagi, tapi janji ‘5 menit doang’ (bohong)", value: "tiduran_lagi" },
            { label: "Langsung ke dapur cari makanan", value: "cari_makanan" },
            { label: "Lihat jam, terus mikir ‘Kenapa gua masih hidup?’", value: "krisis_eksistensial" },
        ],
    },
    alasanGakBalasChat: {
        fieldName: "alasanGakBalasChat",
        emoji: "📱",
        label: `Kenapa lu sering gak balas chat padahal keliatan online?`,
        options: [
            { label: "Baca chatnya, terus lupa bales", value: "lupa_bales" },
            { label: "Liat chat, terus gak mood buat balas", value: "gak_mood" },
            { label: "Bales di kepala doang, nggak di ketik", value: "bales_di_otak" },
            { label: "Mau bales, tapi tiba-tiba HP ilang di kasur", value: "hp_tenggelam" },
        ],
    },
    siapaLuDiFilmHorror: {
        fieldName: "siapaLuDiFilmHorror",
        emoji: "👻",
        label: `Kalau ini film horror, lu bakal jadi siapa?`,
        options: [
            { label: "Orang pertama yang mati", value: "mati_duluan" },
            { label: "Yang dibilang ‘jangan kesana’ tapi tetap kesana", value: "orang_kepo" },
            { label: "Orang yang ngerekam buat konten TikTok", value: "konten_tiktok" },
            { label: "Monster yang sebenernya cuma insecure", value: "monster_insecure" },
        ],
    },
    reaksiDapetHadiahAneh: {
        fieldName: "reaksiDapetHadiahAneh",
        emoji: "🎁",
        label: `Lu dikasih hadiah aneh banget, reaksi lu gimana?`,
        options: [
            { label: "Tetap bilang ‘Wah, makasih!’ walaupun bingung", value: "tetap_sopan" },
            { label: "Langsung gugling ‘Apa gunanya benda ini?’", value: "googling_hadiah" },
            { label: "Mikir ini kode keras atau pesan rahasia?", value: "parno" },
            { label: "Kasih ke orang lain, pura-pura ‘lupa’", value: "dikasih_ke_orang" },
        ],
    },
    superpowerPalingGakGuna: {
        fieldName: "superpowerPalingGakGuna",
        emoji: "🦸",
        label: `Kalau punya kekuatan super yang nggak guna sama sekali, lu mau yang mana?`,
        options: [
            { label: "Bisa bikin nasi goreng tapi cuma pas udah kenyang", value: "nasi_goreng_kenyang" },
            { label: "Bisa tau kapan jemuran tetangga bakal jatuh", value: "jemuran_tetangga" },
            { label: "Bisa menyalakan TV dengan pikiran, tapi selalu channel berita", value: "tv_berita" },
            { label: "Bisa ngilangin bau ketiak, tapi cuma buat orang lain", value: "bau_ketiak_orang" },
        ],
    },
    kebiasaanMakanYangNyebelin: {
        fieldName: "kebiasaanMakanYangNyebelin",
        emoji: "🍽️",
        label: `Dari semua kebiasaan makan ini, mana yang paling nyebelin?`,
        options: [
            { label: "Ngunyah keras banget kayak ASMR live", value: "ngunyah_keras" },
            { label: "Makan Indomie tapi kuahnya dikit banget", value: "indomie_dikit" },
            { label: "Nanya ‘Makan apa?’ tapi gak pernah ikut makan", value: "nanya_tapi_gak_makan" },
            { label: "Nungguin lu ngabisin makanan, padahal gak niat bantu", value: "nontonin_makan" },
        ],
    },
    tipeBilangGakPunyaDuit: {
        fieldName: "tipeBilangGakPunyaDuit",
        emoji: "💸",
        label: `Kalau lagi bokek, cara bilangnya gimana?`,
        options: [
            { label: `"Lagi ngirit dulu, bro"`, value: "lagi_ngirit" },
            { label: `"Bulan ini banyak pengeluaran..." (padahal tiap bulan gitu)`, value: "banyak_pengeluaran" },
            { label: `"Liat dulu deh, ntar gua kabarin" (gak pernah kabarin)`, value: "liat_dulu" },
            { label: `"Aduh, sinyal gua jelek nih..." *langsung hilang*`, value: "sinyal_hilang" },
        ],
    },
    siapaYangKamuPercaya: {
        fieldName: "siapaYangKamuPercaya",
        emoji: "🤨",
        label: `Siapa yang lebih bisa kamu percaya tanpa alasan yang jelas?`,
        options: [
            { label: "Orang yang pake jam tangan di tangan kanan", value: "jam_tangan_kanan" },
            { label: "Tukang parkir yang nggak minta uang", value: "tukang_parkir_gratis" },
            { label: "Orang yang selalu bawa botol minum kemana-mana", value: "botol_minum" },
            { label: "Orang yang gak pernah skip intro Netflix", value: "skip_intro" },
        ],
    },
    kebiasaanBukaHPRandom: {
        fieldName: "kebiasaanBukaHPRandom",
        emoji: "📱",
        label: `Lagi gak ada notif, tapi kamu buka HP. Ngapain?`,
        options: [
            { label: "Buka WhatsApp terus tutup lagi (padahal gak ada chat)", value: "whatsapp_spam" },
            { label: "Scroll TikTok sampe sadar udah sejam", value: "tiktok_lupa_waktu" },
            { label: "Buka galeri, terus liat foto yang sama 3x", value: "galeri_replay" },
            { label: "Cek saldo ShopeePay, padahal gak ada duit", value: "cek_saldo_nol" },
        ],
    },
    kenapaInternetLambat: {
        fieldName: "kenapaInternetLambat",
        emoji: "🌐",
        label: `Internet lagi lemot. Siapa yang harus disalahkan?`,
        options: [
            { label: "Cuaca mendung, pasti ini", value: "cuaca" },
            { label: "Tetangga yang streaming drakor HD", value: "tetangga_streaming" },
            { label: "Provider, karena udah tradisi nyalahin mereka", value: "provider" },
            { label: "Gua sendiri, karena belum bayar tagihan", value: "belum_bayar" },
        ],
    },
    reaksiKagetGakPenting: {
        fieldName: "reaksiKagetGakPenting",
        emoji: "😱",
        label: `Hal kecil yang tiba-tiba bikin kamu panik?`,
        options: [
            { label: "Dompet gak ada di kantong, padahal ditaro di tas", value: "dompet_hilang" },
            { label: "Denger suara ‘kletek-kletek’ di motor", value: "motor_kletek" },
            { label: "HP tiba-tiba panas, langsung mikir bakal meledak", value: "hp_panas" },
            { label: "Buka kulkas, lupa mau ngambil apa", value: "lupa_ambil" },
        ],
    },
    kebiasaanMakanPalingNyebelin: {
        fieldName: "kebiasaanMakanPalingNyebelin",
        emoji: "🍽️",
        label: `Mana kebiasaan makan yang paling nyebelin?`,
        options: [
            { label: "Orang yang ngaduk dulu semua makanan di piring", value: "ngaduk_semua" },
            { label: "Makan Indomie pake nasi", value: "indomie_nasi" },
            { label: "Minum teh manis abis makan, padahal udah makan yang manis juga", value: "teh_manis" },
            { label: "Ngunyah sambil ngobrol biar semua orang denger", value: "ngunyah_speaker" },
        ],
    },
    siapaLuDiTokoBaju: {
        fieldName: "siapaLuDiTokoBaju",
        emoji: "👕",
        label: `Kalau di toko baju, lu tipe yang mana?`,
        options: [
            { label: "Coba-coba baju terus gak beli", value: "coba_doang" },
            { label: "Pegang bahan bajunya kayak fashion expert", value: "fashion_expert" },
            { label: "Liat harga dulu sebelum liat desainnya", value: "cek_harga_dulu" },
            { label: "Ngikut orang lain, padahal gak mau beli", value: "ikut_ngikut" },
        ],
    },
    caraLuNgumpetPasMainPetakUmpet: {
        fieldName: "caraLuNgumpetPasMainPetakUmpet",
        emoji: "🙈",
        label: `Main petak umpet, tapi tempat ngumpet lu harus absurd. Pilih mana?`,
        options: [
            { label: "Di belakang gorden, padahal kaki keliatan", value: "belakang_gorden" },
            { label: "Masuk kulkas, terus sadar ini ide buruk", value: "masuk_kulkas" },
            { label: "Diem aja di tengah ruangan, berharap jadi siluman", value: "siluman" },
            { label: "Dibalik pintu, tapi pintunya transparan", value: "pintu_transparan" },
        ],
    },
    caraLuNgecenginTemen: {
        fieldName: "caraLuNgecenginTemen",
        emoji: "😂",
        label: `Kalau ngecengin temen, lu bakal...?`,
        options: [
            { label: "Ngungkit kesalahan dia 5 tahun lalu", value: "kesalahan_lama" },
            { label: "Bikin julukan random yang stuck selamanya", value: "julukan_stuck" },
            { label: "Ngechat mamanya biar dia kena omel", value: "chat_mama" },
            { label: "Ngedit fotonya jadi meme dan sebarin ke grup", value: "meme_grup" },
        ],
    },
    bendaAnehYangHarusAdaDiTas: {
        fieldName: "bendaAnehYangHarusAdaDiTas",
        emoji: "🎒",
        label: `Dari semua benda absurd ini, mana yang harus ada di tas lu?`,
        options: [
            { label: "Sendok garpu portable, just in case", value: "sendok_garpu" },
            { label: "Obat masuk angin, meskipun sehat-sehat aja", value: "tolak_angin" },
            { label: "Kabel charger semua jenis HP, padahal cuma punya satu HP", value: "kabel_hp" },
            { label: "Plester luka, padahal bukan anak kecil", value: "plester_luka" },
        ],
    },
    caraMakanMartabakPalingAneh: {
        fieldName: "caraMakanMartabakPalingAneh",
        emoji: "🥞",
        label: `Martabak manis enaknya dimakan gimana?`,
        options: [
            { label: "Dilapis semua, terus dimakan kayak burger", value: "burger_martabak" },
            { label: "Pake sendok, biar nggak lengket di tangan", value: "sendok_martabak" },
            { label: "Langsung dari kotaknya, tanpa malu-malu", value: "langsung_kotak" },
            { label: "Dikunyah dulu baru diminum teh manisnya", value: "teh_manis" },
        ],
    },
} as const
