import { FormQuestion } from "../type"

export const ID_FORM_QUESTIONS: Record<string, FormQuestion> = {
    favDateActivity: {
        fieldName: "favDateActivity",
        emoji: "💑",
        label: `Kalau nge-date, paling seru ngapain?`,
        options: [
            { label: "Makan di restoran mahal biar estetik 🤩", value: "fancy_dinner" },
            { label: "Netflix & chill… sambil makan Indomie", value: "netflix_indomie" },
            { label: "Main board game sampe ada yang ngambek 😡", value: "board_game" },
            { label: "Jalan-jalan ke mall sampe kaki pegel 🏃‍♂️", value: "mall" },
        ],
    },
    bathroomEtiquette: {
        fieldName: "bathroomEtiquette",
        emoji: "🚿",
        label: `Di toilet umum, kamu tipe yang...?`,
        options: [
            { label: "Guyur dulu sebelum duduk (biar steril) 🚰", value: "guyur_dulu" },
            { label: "Langsung duduk, biarin aja", value: "langsung" },
            { label: "Manggil emak buat ambilin air", value: "manggil_emak" },
            { label: "Mikirin eksistensi hidup sebelum cebok 🤔", value: "mikir_dulu" },
        ],
    },
    apocalypticSkills: {
        fieldName: "apocalypticSkills",
        emoji: "🧟",
        label: `Tiba-tiba ada serangan zombie, apa yang bakal kamu lakukan?`,
        options: [
            { label: "Lawan pake golok! Aku bukan orang biasa! ⚔️", value: "fighter" },
            { label: "Ngumpet di Indomaret, biar ada stok mie instan", value: "hider" },
            { label: "Masak Indomie buat zombie, biar kita damai 🍜", value: "cook" },
            { label: "Langsung nyerah aja, hidup udah capek", value: "sacrifice" },
        ],
    },
    indomiePreference: {
        fieldName: "indomiePreference",
        emoji: "🍜",
        label: `Makan Indomie paling enak gimana?`,
        options: [
            { label: "Kuah panas, pake telur biar nikmat", value: "kuah" },
            { label: "Goreng, terus ditambah nasi! 🍚", value: "goreng" },
            { label: "Dimakan mentah langsung kaya ciki", value: "mentah" },
            { label: "Dijadiin Indomie burger, coba-coba aja", value: "burger" },
        ],
    },
    ayamGeprekLevel: {
        fieldName: "ayamGeprekLevel",
        emoji: "🌶️",
        label: `Kalau makan ayam geprek, level pedasnya...?`,
        options: [
            { label: "Level 1 aja, takut diare 🥲", value: "level1" },
            { label: "Level 5, masih aman sih", value: "level5" },
            { label: "Level 10! Keringetan itu nikmat", value: "level10" },
            { label: "Level 20++, biar hidup ada tantangan 🔥", value: "level20" },
        ],
    },
    kerokanOrNot: {
        fieldName: "kerokanOrNot",
        emoji: "🪃",
        label: `Kalau masuk angin, apa yang kamu lakukan?`,
        options: [
            { label: "Langsung kerokan, wajib! 🟥🟧", value: "kerokan" },
            { label: "Minum tolak angin dulu", value: "tolak_angin" },
            { label: "Tidur aja, biar sembuh sendiri", value: "tidur" },
            { label: "Masuk angin tuh mitos...", value: "mitos" },
        ],
    },
    idealVacation: {
        fieldName: "idealVacation",
        emoji: "🏝️",
        label: `Kalau liburan bareng pasangan, paling enak ke mana?`,
        options: [
            { label: "Bali! Sunset, pantai, chill...", value: "bali" },
            { label: "Bandung, dingin-dingin romantis", value: "bandung" },
            { label: "Jogja, vibesnya beda", value: "jogja" },
            { label: "Staycation aja di kosan", value: "staycation" },
        ],
    },
    relationshipFights: {
        fieldName: "relationshipFights",
        emoji: "🤬",
        label: `Kalau lagi berantem, kamu biasanya...?`,
        options: [
            { label: "Langsung ngobrol biar cepet baikan", value: "ngobrol" },
            { label: "Diem-dieman dulu, biar ada vibe sinetron", value: "dieman" },
            { label: "Spam meme sampe doi ngakak 😂", value: "meme" },
            { label: "Ngilang, biar doi sadar kalo aku berharga", value: "ngilang" },
        ],
    },
    petChoice: {
        fieldName: "petChoice",
        emoji: "🐾",
        label: `Kalau bisa punya peliharaan, pilih apa?`,
        options: [
            { label: "Kucing, lucu tapi kadang jahat 🐱", value: "cat" },
            { label: "Anjing, setia dan manja 🐶", value: "dog" },
            { label: "Ayam, biar tiap pagi ada alarm alami 🐔", value: "chicken" },
            { label: "Punya pocong peliharaan biar hemat listrik 👻", value: "pocong" },
        ],
    },
    howToEatRice: {
        fieldName: "howToEatRice",
        emoji: "🍚",
        label: `Nasi tuh paling enak dimakan pake apa?`,
        options: [
            { label: "Ayam geprek, combo mantap!", value: "geprek" },
            { label: "Telur dadar, yang penting ada lauk", value: "telur" },
            { label: "Kecap + garam (sad meal)", value: "kecap" },
            { label: "Nasi anget doang (minimalis)", value: "polos" },
        ],
    },
    baksoOrMieAyam: {
        fieldName: "baksoOrMieAyam",
        emoji: "🍜",
        label: `Lagi laper banget. Pilih yang mana?`,
        options: [
            { label: "Bakso, kuahnya seger 🍡", value: "bakso" },
            { label: "Mie ayam, toppingnya banyak! 🥢", value: "mie_ayam" },
            { label: "Dua-duanya, aku anak sultan", value: "dua" },
            { label: "Gua makan nasi pake kecap aja 🥲", value: "irit" },
        ],
    },
    ghostEncounter: {
        fieldName: "ghostEncounter",
        emoji: "👻",
        label: `Tiba-tiba ketemu kuntilanak di jalan. Apa reaksi lo?`,
        options: [
            { label: "Lari sekenceng-kencengnya 🏃‍♂️", value: "lari" },
            { label: "Teriak 'permisi ya kak!' 😬", value: "permisi" },
            { label: "Nawarin rokok biar dia chill 🚬", value: "rokok" },
            { label: "Gue cuekin, biar dia insecure", value: "cuek" },
        ],
    },
    losingSignal: {
        fieldName: "losingSignal",
        emoji: "📶",
        label: `Lagi chatting penting banget, terus sinyal ilang. Apa yang lo lakuin?`,
        options: [
            { label: "Restart HP, pasti berhasil 🔄", value: "restart" },
            { label: "Pindah ke tempat lebih tinggi, kaya Naruto 🌄", value: "pindah" },
            { label: "Chat ulang dari awal, males nunggu", value: "ulang" },
            { label: "Pasrah, mungkin ini pertanda dari semesta", value: "pasrah" },
        ],
    },
    relationshipFinance: {
        fieldName: "relationshipFinance",
        emoji: "💸",
        label: `Siapa yang harus bayar pas kencan pertama?`,
        options: [
            { label: "Cowok dong, gentlemen vibes", value: "cowok" },
            { label: "Cewek, biar beda aja 😎", value: "cewek" },
            { label: "Patungan, kita kan tim", value: "split" },
            { label: "Gua ngilang sebelum bayar 🚶‍♂️", value: "ngilang" },
        ],
    },
    karaokeStyle: {
        fieldName: "karaokeStyle",
        emoji: "🎤",
        label: `Kalo karaokean, lo tipe yang...?`,
        options: [
            { label: "Nyanyi all out, suara pas-pasan bodo amat!", value: "all_out" },
            { label: "Cuma milih lagu tapi nggak nyanyi", value: "pilih_lagu" },
            { label: "Nunggu lagu mellow biar bisa curhat 🥀", value: "mellow" },
            { label: "Nari doang, nggak ikutan nyanyi", value: "nari" },
        ],
    },
    trafficJamReaction: {
        fieldName: "trafficJamReaction",
        emoji: "🚗",
        label: `Lagi macet total, terus lo...?`,
        options: [
            { label: "Diem aja, pasrah", value: "pasrah" },
            { label: "Nyetel lagu keras-keras biar happy 🎶", value: "musik" },
            { label: "Ngomel-ngomel ke supir (walaupun naik Gojek)", value: "ngomel" },
            { label: "Nyoba tidur tapi gagal", value: "tidur" },
        ],
    },
    horrorMovieStyle: {
        fieldName: "horrorMovieStyle",
        emoji: "🎥",
        label: `Kalo nonton film horror, lo tipe yang...?`,
        options: [
            { label: "Tutup mata, tapi intip dikit", value: "intip" },
            { label: "Teriak duluan sebelum hantunya muncul", value: "teriak" },
            { label: "Santai, malah ngakak", value: "ngakak" },
            { label: "Tidur, film horror nggak efek ke gue", value: "tidur" },
        ],
    },
    nasiGorengStyle: {
        fieldName: "nasiGorengStyle",
        emoji: "🍳",
        label: `Nasi goreng enaknya pake apa?`,
        options: [
            { label: "Telur ceplok, wajib!", value: "telur" },
            { label: "Makan polosan aja, minimalis", value: "polos" },
            { label: "Dibanjur kecap biar manis", value: "kecap" },
            { label: "Tambah cabe biar berkeringat! 🌶️", value: "pedas" },
        ],
    },
    yourSleepHabits: {
        fieldName: "yourSleepHabits",
        emoji: "😴",
        label: `Gimana kebiasaan tidur lo?`,
        options: [
            { label: "Tidur teratur, jam 10 udah bobok", value: "teratur" },
            { label: "Tidur jam 3 pagi, bangun siang", value: "begadang" },
            { label: "Tidur cuma buat ngisi waktu kosong", value: "random" },
            { label: "Gak tidur, gue vampir", value: "insomnia" },
        ],
    },
    onlineShopping: {
        fieldName: "onlineShopping",
        emoji: "📦",
        label: `Liat diskon gede di e-commerce, lo...?`,
        options: [
            { label: "Langsung checkout, rezeki nggak boleh ditolak!", value: "checkout" },
            { label: "Masukin keranjang, tapi nggak beli", value: "keranjang" },
            { label: "Bandingin harga di 5 toko dulu 🧐", value: "bandingin" },
            { label: "Nunggu gajian baru beli 🥲", value: "nunggu_gajian" },
        ],
    },
    sambalToleransi: {
        fieldName: "sambalToleransi",
        emoji: "🌶️",
        label: `Seberapa pedas sambal yang lo sanggup makan?`,
        options: [
            { label: "Cuma sambal bawang, lebih dari itu kapok", value: "bawang" },
            { label: "Sambal terasi, masih aman dikit", value: "terasi" },
            { label: "Sambal setan! Airmata & keringat bersatu!", value: "setan" },
            { label: "Sambal? Gue minum BonCabe langsung", value: "boncabe" },
        ],
    },
    extremeBoardGame: {
        fieldName: "extremeBoardGame",
        emoji: "🎲",
        label: `Kalau main board game sama pasangan, lo tipe yang...?`,
        options: [
            { label: "Santai, yang penting have fun", value: "santai" },
            { label: "Gue main serius, gak ada ampun", value: "serius" },
            { label: "Curang dikit boleh dong 😉", value: "curang" },
            { label: "Ngambek kalo kalah, harus menang!", value: "ngambek" },
        ],
    },
    annoyingHabits: {
        fieldName: "annoyingHabits",
        emoji: "🤨",
        label: `Kebiasaan paling ngeselin yang lo punya?`,
        options: [
            { label: "Nggak bales chat, tapi aktif di sosmed", value: "no_reply" },
            { label: "Ngambil makanan orang tanpa izin", value: "food_stealer" },
            { label: "Ngupil terus lupa cuci tangan", value: "ngupil" },
            { label: "Ngorok keras sampe bikin gempa", value: "ngorok" },
        ],
    },
    durianOpinion: {
        fieldName: "durianOpinion",
        emoji: "🍈",
        label: `Durian itu...?`,
        options: [
            { label: "Surga dunia! Bau harum banget", value: "suka" },
            { label: "Bau kamar mandi umum, nggak suka", value: "benci" },
            { label: "Makan kalau gratis aja", value: "gratis" },
            { label: "Durian es krim oke, yang asli NOPE", value: "eskrim" },
        ],
    },
    phoneBattery: {
        fieldName: "phoneBattery",
        emoji: "🔋",
        label: `Baterai HP tinggal 2%. Apa yang lo lakuin?`,
        options: [
            { label: "Panikan! Langsung cari colokan", value: "panik" },
            { label: "Mode hemat daya, jaga-jaga", value: "hemat" },
            { label: "Santai, mati ya mati", value: "mati_aja" },
            { label: "Malah nonton TikTok sampe beneran mati", value: "tiktok" },
        ],
    },
    warungIndomieStyle: {
        fieldName: "warungIndomieStyle",
        emoji: "🍜",
        label: `Makan Indomie di warung tuh wajib pake...?`,
        options: [
            { label: "Telur ceplok, biar mantep!", value: "telur" },
            { label: "Kornet, favorit sejuta umat", value: "kornet" },
            { label: "Keju! Biar fancy dikit 🧀", value: "keju" },
            { label: "Cuma kuah doang, anak kos mode", value: "polos" },
        ],
    },
    sleepPosition: {
        fieldName: "sleepPosition",
        emoji: "🛏️",
        label: `Posisi tidur favorit lo?`,
        options: [
            { label: "Telentang, ala mayat 🛌", value: "telentang" },
            { label: "Meringkuk kaya udang 🦐", value: "udang" },
            { label: "Perut ke bawah, napas dikit-dikit", value: "perut" },
            { label: "Gak punya posisi tetap, kayak ninja", value: "random" },
        ],
    },
    waitingForFood: {
        fieldName: "waitingForFood",
        emoji: "⌛",
        label: `Lagi laper berat, terus makanan lo lama banget dateng. Apa yang lo lakuin?`,
        options: [
            { label: "Diem aja, sabar menunggu", value: "sabar" },
            { label: "Curi makanan temen duluan", value: "curi" },
            { label: "Main HP biar gak kepikiran", value: "main_hp" },
            { label: "Komplen ke abang warung biar buru-buru", value: "komplen" },
        ],
    },
    horrorSuperpower: {
        fieldName: "horrorSuperpower",
        emoji: "🦸‍♂️",
        label: `Kalau punya kekuatan di film horror, lo lebih suka yang mana?`,
        options: [
            { label: "Bisa ngilang biar gak dikejar hantu", value: "ngilang" },
            { label: "Bisa ngobrol sama hantu, jadi bestie 👻", value: "bestie_hantu" },
            { label: "Kekuatan tinju biar hantunya babak belur", value: "tinju" },
            { label: "Slow motion kaya di iklan sabun", value: "slow_mo" },
        ],
    },
    karaokeSongChoice: {
        fieldName: "karaokeSongChoice",
        emoji: "🎤",
        label: `Kalau disuruh nyanyi di karaoke, lagu wajib lo apa?`,
        options: [
            { label: "Dewa 19 - Kangen 🎸", value: "dewa" },
            { label: "Tulus - Hati-hati di Jalan 😭", value: "tulus" },
            { label: "Ayamku - Denny Caknan 🐔", value: "ayamku" },
            { label: "Lagu JKT48 biar semangat!", value: "jkt48" },
        ],
    },
    martabakTopping: {
        fieldName: "martabakTopping",
        emoji: "🥞",
        label: `Martabak manis paling enak pake topping apa?`,
        options: [
            { label: "Coklat kacang, klasik terbaik", value: "coklat_kacang" },
            { label: "Keju doang, elegan", value: "keju" },
            { label: "Campur SEMUANYA sampe berat banget", value: "campur" },
            { label: "Gak suka martabak, aku agen asing", value: "anti_martabak" },
        ],
    },
    streetFoodHygiene: {
        fieldName: "streetFoodHygiene",
        emoji: "🍢",
        label: `Liat abang jualan gorengan tangannya abis megang duit, reaksi lo?`,
        options: [
            { label: "Gas aja, virus bisa kalah sama minyak goreng", value: "gas" },
            { label: "Minta dia cuci tangan dulu", value: "cuci" },
            { label: "Diem tapi dalem hati nangis", value: "nangis" },
            { label: "Langsung pergi, perut gua berharga", value: "pergi" },
        ],
    },
    cheatingOnExam: {
        fieldName: "cheatingOnExam",
        emoji: "📝",
        label: `Ujian, lo tipe yang...?`,
        options: [
            { label: "Belajar mati-matian kayak anak sholeh", value: "belajar" },
            { label: "Contek dikit gapapa kan ya?", value: "contek" },
            { label: "Bikin catatan kecil di botol minum", value: "botol" },
            { label: "Minta jawaban terang-terangan", value: "minta" },
        ],
    },
    indomieCursed: {
        fieldName: "indomieCursed",
        emoji: "🍜",
        label: `Cara makan Indomie paling GAK MASUK AKAL tapi lo tetep lakuin?`,
        options: [
            { label: "Dijadiin sandwich pake roti", value: "sandwich" },
            { label: "Dibuat jadi pancake", value: "pancake" },
            { label: "Dimasukin ES BATU biar dingin", value: "es_batu" },
            { label: "Makan Indomie pake nasi (anak Indonesia sejati)", value: "nasi" },
        ],
    },
    ghostDare: {
        fieldName: "ghostDare",
        emoji: "👻",
        label: `Disuruh uji nyali di kuburan, lo bakal...?`,
        options: [
            { label: "Gas! Gak takut!", value: "gas" },
            { label: "Bilang 'Sorry ya bang, numpang lewat'", value: "permisi" },
            { label: "Langsung kabur sebelum mulai", value: "kabur" },
            { label: "Pura-pura kesurupan biar dipulangin", value: "kesurupan" },
        ],
    },
    foodStealing: {
        fieldName: "foodStealing",
        emoji: "🍕",
        label: `Lo sering ngambil makanan orang lain tanpa izin?`,
        options: [
            { label: "Sering, kalo gak ketahuan artinya halal", value: "sering" },
            { label: "Kadang, tapi cuma ke temen deket", value: "kadang" },
            { label: "Gue cuma minta, gak nyolong!", value: "minta" },
            { label: "Gue lebih sering jadi korban", value: "korban" },
        ],
    },
    breakUpMethod: {
        fieldName: "breakUpMethod",
        emoji: "💔",
        label: `Kalo putus, cara terbaik menurut lo...?`,
        options: [
            { label: "Ngomong langsung, kayak orang dewasa", value: "dewasa" },
            { label: "Ngilang aja sampe doi ngerti sendiri", value: "ghosting" },
            { label: "Putus lewat chat biar nggak awkward", value: "chat" },
            { label: "Bikin doi kesel dulu biar dia yang mutusin", value: "manipulasi" },
        ],
    },
    washingDishes: {
        fieldName: "washingDishes",
        emoji: "🍽️",
        label: `Lagi numpang makan di rumah temen, lo bakal...?`,
        options: [
            { label: "Cuci piring sendiri, biar sopan", value: "cuci" },
            { label: "Tinggalin aja, biar tuan rumah yang cuci", value: "tinggalin" },
            { label: "Gue bantu nyusun piring, minimal effort", value: "minimal" },
            { label: "Pura-pura sibuk biar gak disuruh cuci", value: "pura_pura" },
        ],
    },
    horrorMovieSurvival: {
        fieldName: "horrorMovieSurvival",
        emoji: "🎬",
        label: `Lo kalo jadi karakter di film horror, bakal...?`,
        options: [
            { label: "Jadi yang mati pertama", value: "mati_duluan" },
            { label: "Survive sampe akhir, tapi trauma", value: "selamat" },
            { label: "Jadi yang sok berani tapi kena karma", value: "karma" },
            { label: "Join sama hantunya, males kabur", value: "gabung" },
        ],
    },
    spicyRelationship: {
        fieldName: "spicyRelationship",
        emoji: "🔥",
        label: `Kalo pacaran, lo tipe...?`,
        options: [
            { label: "Bucin akut, 24/7 chat", value: "bucin" },
            { label: "Santai aja, gak perlu tiap hari kontak", value: "santai" },
            { label: "Doyan ngegas kalo telat bales", value: "ngegas" },
            { label: "Gue sering lupa balas chat 😅", value: "lupa" },
        ],
    },
    sideOfBed: {
        fieldName: "sideOfBed",
        emoji: "🛏️",
        label: `Kalo tidur bareng, lo harus di sisi mana?`,
        options: [
            { label: "Kiri, pokoknya harus kiri!", value: "kiri" },
            { label: "Kanan, gak bisa tidur kalo di kiri", value: "kanan" },
            { label: "Gak peduli, yang penting empuk", value: "bebas" },
            { label: "Gak peduli, karena gue nguasain seluruh kasur", value: "diktator" },
        ],
    },
    reactionToBeingIgnored: {
        fieldName: "reactionToBeingIgnored",
        emoji: "😠",
        label: `Kalo lagi chat terus doi lama balesnya, lo bakal...?`,
        options: [
            { label: "Santai aja, mungkin dia sibuk", value: "santai" },
            { label: "Nungguin sambil stalking story", value: "stalking" },
            { label: "Chat '??' biar dia tau gue nunggu", value: "question_marks" },
            { label: "Bales lebih lama biar impas", value: "balas_dendam" },
        ],
    },
    whoEatsTheLastBite: {
        fieldName: "whoEatsTheLastBite",
        emoji: "🍕",
        label: `Lagi makan berdua, tinggal satu suapan terakhir. Siapa yang harus makan?`,
        options: [
            { label: "Gue, karena gue yang paling butuh", value: "gue" },
            { label: "Doi, biar keliatan sweet", value: "doi" },
            { label: "Dipisah biar adil", value: "dipisah" },
            { label: "Gak ada yang makan sampe basi", value: "gak_ada" },
        ],
    },
    reactionToEmbarrassment: {
        fieldName: "reactionToEmbarrassment",
        emoji: "😳",
        label: `Lagi jalan di mall, tiba-tiba lo kepleset di depan banyak orang. Lo bakal...?`,
        options: [
            { label: "Cepet-cepet bangun pura-pura gak terjadi apa-apa", value: "pura_pura" },
            { label: "Ketawa sendiri biar gak malu", value: "ketawa" },
            { label: "Ngeliatin lantai dengan penuh kebencian", value: "lantai" },
            { label: "Langsung kabur ke toilet terdekat", value: "kabur" },
        ],
    },
    spicyFoodCompetition: {
        fieldName: "spicyFoodCompetition",
        emoji: "🌶️",
        label: `Ada tantangan makan mie pedes level 100, lo...?`,
        options: [
            { label: "Gas! Pantang mundur", value: "gas" },
            { label: "Coba dikit, terus nyesel", value: "nyesel" },
            { label: "Nonton temen menderita sambil ketawa", value: "nonton" },
            { label: "Gak mau, perut gua bukan besi", value: "menolak" },
        ],
    },
    childhoodCartoon: {
        fieldName: "childhoodCartoon",
        emoji: "📺",
        label: `Kartun masa kecil yang paling lo inget?`,
        options: [
            { label: "Spongebob, golden era TV", value: "spongebob" },
            { label: "Doraemon, setiap minggu wajib nonton", value: "doraemon" },
            { label: "Upin Ipin, bestie masa kecil", value: "upin_ipin" },
            { label: "Tom & Jerry, isinya cuma kejar-kejaran", value: "tom_jerry" },
        ],
    },
    reactionToSeeingCelebrity: {
        fieldName: "reactionToSeeingCelebrity",
        emoji: "🤩",
        label: `Ketemu artis terkenal di tempat umum, lo bakal...?`,
        options: [
            { label: "Minta foto dong!", value: "foto" },
            { label: "Liatin aja dari jauh, biar gak ganggu", value: "liatin" },
            { label: "Pura-pura gak peduli, padahal excited", value: "sok_cuek" },
            { label: "Gak kenal, cuek aja", value: "gak_kenal" },
        ],
    },
    findingMoneyOnTheGround: {
        fieldName: "findingMoneyOnTheGround",
        emoji: "💰",
        label: `Lagi jalan, nemu duit 100 ribu di jalan. Lo bakal...?`,
        options: [
            { label: "Ambil dong! Rezeki jangan ditolak", value: "ambil" },
            { label: "Liat sekitar dulu, takut ada yang liat", value: "hati_hati" },
            { label: "Cari pemiliknya, takut karma", value: "jujur" },
            { label: "Diamkan, takut itu jebakan polisi", value: "jebakan" },
        ],
    },
    ketchupOrChiliSauce: {
        fieldName: "ketchupOrChiliSauce",
        emoji: "🍅",
        label: `Lo tim kecap atau tim saus sambal?`,
        options: [
            { label: "Tim kecap, yang penting manis", value: "kecap" },
            { label: "Tim saus sambal, makin pedes makin enak", value: "sambal" },
            { label: "Campur dua-duanya biar maksimal", value: "campur" },
            { label: "Gak suka dua-duanya, anak alien", value: "gak_suka" },
        ],
    },
    gettingCaughtSleepingInClass: {
        fieldName: "gettingCaughtSleepingInClass",
        emoji: "😴",
        label: `Ketiduran di kelas, terus ketauan guru. Lo bakal...?`,
        options: [
            { label: "Ngaku aja, 'Maaf Pak/Bu, ngantuk banget'", value: "ngaku" },
            { label: "Pura-pura melek tapi mata masih setengah ketutup", value: "melek_pura" },
            { label: "Langsung jawab 'Saya denger kok Bu/Pak!'", value: "jawab_dulu" },
            { label: "Nuduh temen sebelah yang sebenernya gak salah", value: "nuduh" },
        ],
    },
} as const
